=== SDFIdk/genericode-transformer/src/main/xml/schemas/xsd/message-catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    version="1.0"
    xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80"
    xmlns:msg="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xsd:import
        namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="xml.xsd" />

    <xsd:element name="messages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="message"
                    maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:simpleContent>
                            <xsd:extension base="xsd:string">
                                <xsd:attribute
                                    name="id"
                                    type="xsd:ID"
                                    use="required" />
                            </xsd:extension>
                        </xsd:simpleContent>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute
                ref="xml:lang"
                use="required" />
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== SDFIdk/genericode-transformer/src/main/resources/locale/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages
    xml:lang="en"
    xmlns="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80 ../../xml/schemas/xsd/message-catalog.xsd ">
    
    <!-- Register metadata -->
    <message id="registeremailmessage">Email us for code list enquiries</message>
    <message id="registergdprmessage">Note: If you send us an email, the information will be registered in our centralised digital system for further processing.</message>
    <message id="registername">Code list register</message>
    <message id="registerowner">Agency for Climate Data</message>
    
    <!-- Navigation -->
    <message id="backtofrontpage">Tilbage til register</message>
    
    <!-- Headings -->
    <message id="data">Data</message>
    <message id="download">Download</message>
    <message id="metadata">Metadata</message>
    
    <!-- Metadata -->
    <message id="agency">Owner</message>
    <message id="alternateformatlocationuri">Download URL</message>
    <message id="available">Publication date</message>
    <message id="canonicaluri">Unique id</message>
    <message id="canonicalversionuri">Unique version id</message>
    <message id="description">Description</message>
    <message id="license">License</message>
    <message id="locationuri">Download URL</message>
    <message id="provenance">Provenance</message>
    <message id="publisher">Publisher</message>
    <message id="shortname">Short name</message>
    <message id="source">Source</message>
    <message id="version">Version</message>
</messages>

=== SDFIdk/genericode-transformer/src/main/resources/locale/da.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages
    xml:lang="da"
    xmlns="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:uuid:74875954-5193-4fb8-ba48-9944e9a36c80 ../../xml/schemas/xsd/message-catalog.xsd ">
    
    <!-- Register metadata -->
    <message id="registeremailmessage">Send en e-mail med en henvendelse om selve kodelisteregistret</message>
    <message id="registergdprmessage">Bemærk: Sender du os en e-mail, vil oplysningerne blive registreret i vores centrale, digitale system til videre sagsbehandling.</message>
    <message id="registerscopemessage">Bemærk: Henvendelser om de enkelte kodelister skal rettes til de respektive registerejere.</message>
    <message id="registername">Kodelisteregister</message>
    <message id="registerowner">Klimadatastyrelsen</message>
    
    <!-- Navigation -->
    <message id="frontpage">forsiden</message>
    
    <!-- Front page -->
    <message id="subregisters">Registre</message>
    
    <!-- Code list overview page -->
    <message id="allversions">alle versioner</message>
    <message id="codelists">Kodelister</message>
    <message id="latestversion">seneste version</message>
    
    <!-- Code list versions overview page -->
    <message id="aboutversions">Versioner af kodelister</message>
    <message id="chooseversion">Vælg version af kodeliste</message>
    <message id="codelistoverviewmanchet1">Her er versionerne af kodelisten</message>
    <message id="readaboutversions">Læs om versionering af kodelister på</message>
    
    <!-- Code list version page -->
    <message id="data">Data</message>
    <message id="download">Download</message>
    <message id="metadata">Metadata</message>
    
    <!-- Code list metadata -->
    <message id="agency">Ejer</message>
    <message id="alternateformatlocationuri">Download-URL</message>
    <message id="available">Udgivelsesdato</message>
    <message id="canonicaluri">Unik id</message>
    <message id="canonicalversionuri">Unik id for version</message>
    <message id="description">Beskrivelse</message>
    <message id="license">Licens</message>
    <message id="locationuri">Download-URL</message>
    <message id="provenance">Versionshistorik</message>
    <message id="shortname">Kort navn</message>
    <message id="source">Kilde</message>
    <message id="version">Version</message>
</messages>
